### ISSUE TITLE
padding 无效

### ISSUE THREAD

**Issue by seekcx** [charleslo1/vue-pin#1]
不管怎么设置 padding 都没有作用。

```vue
 v-pin="{padding: {top: 20}}"
```

![image](https://user-images.githubusercontent.com/8244814/36679980-85d542ea-1b4f-11e8-83fc-3ee3aee76395.png)
生成的样式却是这样

**Comment by charleslo1** [comment]
抱歉，今天才看到。谢谢反馈，问题已经修复了。
